import type { Pool } from "mysql2/promise";

export const INTEGRATION_TABLES = [
  "integration_connectors",
  "integration_connector_reviews",
  "integration_connections",
  "integration_auth_transactions",
  "integration_credentials",
  "integration_tool_snapshots",
  "integration_tool_grants",
  "integration_policies",
  "integration_approvals",
  "integration_tool_calls",
  "integration_call_events",
  "integration_business_links",
  "integration_webhook_subscriptions",
  "integration_events",
  "integration_circuit_states",
  "integration_usage_daily",
  "integration_artifacts",
  "integration_local_runner_pairings",
  "integration_local_runners",
  "integration_local_runner_tasks",
  "integration_local_runner_task_events"
] as const;

type SchemaExecutor = Pick<Pool, "query">;

const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS integration_connectors (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    version VARCHAR(40) NOT NULL,
    connector_type VARCHAR(32) NOT NULL,
    trust_level VARCHAR(24) NOT NULL,
    connector_status VARCHAR(24) NOT NULL,
    team_id VARCHAR(64) NOT NULL DEFAULT '',
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000) NOT NULL DEFAULT '',
    manifest_json JSON NOT NULL,
    manifest_hash CHAR(64) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_integration_connector_version (code, version, team_id),
    KEY idx_integration_connector_team_updated (team_id, updated_at),
    KEY idx_integration_connector_status (connector_status, updated_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_connector_reviews (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    connector_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    review_status VARCHAR(24) NOT NULL,
    manifest_hash CHAR(64) NOT NULL,
    submitted_by VARCHAR(64) NOT NULL,
    reviewed_by VARCHAR(64) NOT NULL DEFAULT '',
    review_note VARCHAR(1000) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_integration_connector_review (connector_id),
    KEY idx_integration_connector_review_status (review_status, updated_at),
    KEY idx_integration_connector_review_team (team_id, updated_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_connections (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    connector_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(64) NOT NULL,
    connection_scope VARCHAR(16) NOT NULL,
    scope_id VARCHAR(64) NOT NULL,
    connection_status VARCHAR(40) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    webhook_public_id VARCHAR(80) NOT NULL,
    revision_no INT UNSIGNED NOT NULL DEFAULT 1,
    last_health_at DATETIME(3) NULL,
    last_health_latency_ms INT UNSIGNED NOT NULL DEFAULT 0,
    last_error_code VARCHAR(80) NOT NULL DEFAULT '',
    last_error_message VARCHAR(500) NOT NULL DEFAULT '',
    server_info_json JSON NULL,
    warning_message VARCHAR(500) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    disconnected_at DATETIME(3) NULL,
    KEY idx_integration_connection_team_updated (team_id, updated_at),
    KEY idx_integration_connection_owner_updated (owner_id, updated_at),
    KEY idx_integration_connection_status (connector_id, connection_status),
    UNIQUE KEY uk_integration_connection_webhook_public (webhook_public_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_auth_transactions (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    connection_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(64) NOT NULL,
    transaction_status VARCHAR(32) NOT NULL,
    state_hash CHAR(64) NOT NULL,
    nonce_hash CHAR(64) NOT NULL,
    encrypted_pkce_verifier LONGTEXT NULL,
    redirect_uri VARCHAR(500) NOT NULL,
    issuer VARCHAR(500) NOT NULL DEFAULT '',
    resource_uri VARCHAR(500) NOT NULL DEFAULT '',
    expires_at DATETIME(3) NOT NULL,
    consumed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_integration_auth_state (state_hash),
    UNIQUE KEY uk_integration_auth_nonce (nonce_hash),
    KEY idx_integration_auth_expiry (expires_at, transaction_status),
    KEY idx_integration_auth_connection (connection_id, transaction_status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_credentials (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    connection_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    credential_type VARCHAR(40) NOT NULL,
    encrypted_value LONGTEXT NOT NULL,
    key_version VARCHAR(32) NOT NULL,
    token_fingerprint CHAR(64) NOT NULL DEFAULT '',
    expires_at DATETIME(3) NULL,
    refreshed_at DATETIME(3) NULL,
    revoked_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_integration_credential_type (connection_id, credential_type),
    KEY idx_integration_credential_expiry (expires_at, revoked_at),
    KEY idx_integration_credential_team (team_id, updated_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_tool_snapshots (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    connection_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    remote_name VARCHAR(200) NOT NULL,
    stable_alias VARCHAR(200) NOT NULL DEFAULT '',
    display_name VARCHAR(200) NOT NULL,
    description VARCHAR(2000) NOT NULL DEFAULT '',
    input_schema_json JSON NOT NULL,
    output_schema_json JSON NULL,
    schema_hash CHAR(64) NOT NULL,
    risk_level TINYINT UNSIGNED NOT NULL DEFAULT 0,
    tool_status VARCHAR(32) NOT NULL,
    revision_no INT UNSIGNED NOT NULL DEFAULT 1,
    discovered_at DATETIME(3) NOT NULL,
    reviewed_at DATETIME(3) NULL,
    reviewed_by VARCHAR(64) NOT NULL DEFAULT '',
    permission_code VARCHAR(80) NOT NULL DEFAULT '',
    review_json JSON NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_integration_tool_schema (connection_id, remote_name, schema_hash),
    KEY idx_integration_tool_connection_status (connection_id, tool_status),
    KEY idx_integration_tool_team_updated (team_id, updated_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_tool_grants (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    tool_snapshot_id VARCHAR(64) NOT NULL,
    connection_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    subject_type VARCHAR(24) NOT NULL,
    subject_id VARCHAR(64) NOT NULL,
    permission_code VARCHAR(40) NOT NULL,
    grant_status VARCHAR(24) NOT NULL,
    constraints_json JSON NULL,
    granted_by VARCHAR(64) NOT NULL,
    expires_at DATETIME(3) NULL,
    revoked_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_integration_tool_grant (tool_snapshot_id, subject_type, subject_id, permission_code),
    KEY idx_integration_grant_subject (team_id, subject_type, subject_id, grant_status),
    KEY idx_integration_grant_tool (tool_snapshot_id, grant_status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_policies (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    team_id VARCHAR(64) NOT NULL,
    connection_id VARCHAR(64) NOT NULL DEFAULT '',
    tool_snapshot_id VARCHAR(64) NOT NULL DEFAULT '',
    policy_type VARCHAR(40) NOT NULL,
    policy_status VARCHAR(24) NOT NULL,
    policy_json JSON NOT NULL,
    revision_no INT UNSIGNED NOT NULL DEFAULT 1,
    created_by VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    KEY idx_integration_policy_team_updated (team_id, updated_at),
    KEY idx_integration_policy_target (connection_id, tool_snapshot_id, policy_status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_approvals (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    team_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(64) NOT NULL,
    connection_id VARCHAR(64) NOT NULL,
    tool_snapshot_id VARCHAR(64) NOT NULL,
    call_id VARCHAR(64) NOT NULL DEFAULT '',
    approval_status VARCHAR(24) NOT NULL,
    risk_level TINYINT UNSIGNED NOT NULL,
    frozen_input_hash CHAR(64) NOT NULL,
    single_use_nonce_hash CHAR(64) NOT NULL,
    requested_by VARCHAR(64) NOT NULL,
    decided_by VARCHAR(64) NOT NULL DEFAULT '',
    decision_note VARCHAR(1000) NOT NULL DEFAULT '',
    expires_at DATETIME(3) NOT NULL,
    decided_at DATETIME(3) NULL,
    consumed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_integration_approval_nonce (single_use_nonce_hash),
    KEY idx_integration_approval_team_status (team_id, approval_status, created_at),
    KEY idx_integration_approval_expiry (expires_at, approval_status),
    KEY idx_integration_approval_call (call_id, approval_status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_tool_calls (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    request_id VARCHAR(100) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(64) NOT NULL,
    actor_id VARCHAR(64) NOT NULL,
    actor_auth_version INT UNSIGNED NOT NULL DEFAULT 1,
    connection_id VARCHAR(64) NOT NULL,
    tool_snapshot_id VARCHAR(64) NOT NULL,
    approval_id VARCHAR(64) NOT NULL DEFAULT '',
    call_status VARCHAR(40) NOT NULL,
    risk_level TINYINT UNSIGNED NOT NULL,
    input_hash CHAR(64) NOT NULL,
    input_artifact_id VARCHAR(64) NOT NULL DEFAULT '',
    input_summary_json JSON NULL,
    output_hash CHAR(64) NOT NULL DEFAULT '',
    result_artifact_id VARCHAR(64) NOT NULL DEFAULT '',
    output_summary_json JSON NULL,
    idempotency_key_hash CHAR(64) NOT NULL,
    external_receipt VARCHAR(500) NOT NULL DEFAULT '',
    evidence_json JSON NULL,
    error_code VARCHAR(100) NOT NULL DEFAULT '',
    error_message VARCHAR(1000) NOT NULL DEFAULT '',
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    queued_at DATETIME(3) NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_integration_call_request (request_id),
    UNIQUE KEY uk_integration_call_idempotency (idempotency_key_hash, connection_id, tool_snapshot_id),
    KEY idx_integration_call_team_status (team_id, call_status, created_at),
    KEY idx_integration_call_actor (actor_id, created_at),
    KEY idx_integration_call_connection (connection_id, call_status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_call_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    call_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    actor_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    from_status VARCHAR(40) NOT NULL DEFAULT '',
    to_status VARCHAR(40) NOT NULL DEFAULT '',
    request_id VARCHAR(100) NOT NULL,
    input_hash CHAR(64) NOT NULL DEFAULT '',
    output_hash CHAR(64) NOT NULL DEFAULT '',
    summary_json JSON NULL,
    created_at DATETIME(3) NOT NULL,
    KEY idx_integration_call_event_call (call_id, id),
    KEY idx_integration_call_event_team (team_id, created_at),
    KEY idx_integration_call_event_actor (actor_id, created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_business_links (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    call_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(64) NOT NULL,
    object_type VARCHAR(40) NOT NULL,
    object_id VARCHAR(64) NOT NULL,
    operation VARCHAR(80) NOT NULL,
    external_object_id VARCHAR(500) NOT NULL DEFAULT '',
    external_thread_id VARCHAR(500) NOT NULL DEFAULT '',
    writeback_status VARCHAR(24) NOT NULL DEFAULT 'pending',
    next_action_at VARCHAR(100) NOT NULL DEFAULT '',
    metadata_json JSON NULL,
    last_error VARCHAR(500) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_integration_business_call (call_id),
    KEY idx_integration_business_object (team_id, owner_id, object_type, object_id),
    KEY idx_integration_business_thread (team_id, owner_id, external_thread_id),
    KEY idx_integration_business_writeback (writeback_status, updated_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_webhook_subscriptions (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    connection_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    remote_subscription_id VARCHAR(200) NOT NULL DEFAULT '',
    resource VARCHAR(500) NOT NULL,
    change_types VARCHAR(100) NOT NULL,
    client_state_hash CHAR(64) NOT NULL,
    subscription_status VARCHAR(32) NOT NULL,
    expires_at DATETIME(3) NULL,
    last_error_code VARCHAR(100) NOT NULL DEFAULT '',
    last_error_message VARCHAR(1000) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    UNIQUE KEY uk_integration_webhook_resource (connection_id, resource),
    KEY idx_integration_webhook_expiry (subscription_status, expires_at),
    KEY idx_integration_webhook_team (team_id, updated_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_events (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    connection_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    external_event_id VARCHAR(200) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_status VARCHAR(32) NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    artifact_id VARCHAR(64) NOT NULL DEFAULT '',
    result_artifact_id VARCHAR(64) NOT NULL DEFAULT '',
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    result_json JSON NULL,
    writeback_status VARCHAR(24) NOT NULL DEFAULT 'not_applicable',
    linked_object_id VARCHAR(64) NOT NULL DEFAULT '',
    last_error_code VARCHAR(100) NOT NULL DEFAULT '',
    last_error_message VARCHAR(1000) NOT NULL DEFAULT '',
    next_attempt_at DATETIME(3) NULL,
    processing_lease_id VARCHAR(64) NOT NULL DEFAULT '',
    processing_lease_expires_at DATETIME(3) NULL,
    received_at DATETIME(3) NOT NULL,
    processed_at DATETIME(3) NULL,
    business_written_at DATETIME(3) NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_integration_external_event (connection_id, external_event_id),
    KEY idx_integration_event_team_status (team_id, event_status, received_at),
    KEY idx_integration_event_retry (next_attempt_at, event_status),
    KEY idx_integration_event_lease (event_status, processing_lease_expires_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_circuit_states (
    subject_type VARCHAR(16) NOT NULL,
    subject_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    connection_id VARCHAR(64) NOT NULL,
    circuit_state VARCHAR(16) NOT NULL DEFAULT 'closed',
    consecutive_failures INT UNSIGNED NOT NULL DEFAULT 0,
    consecutive_successes INT UNSIGNED NOT NULL DEFAULT 0,
    opened_at DATETIME(3) NULL,
    open_until DATETIME(3) NULL,
    last_checked_at DATETIME(3) NULL,
    last_latency_ms INT UNSIGNED NOT NULL DEFAULT 0,
    last_error_code VARCHAR(100) NOT NULL DEFAULT '',
    last_error_message VARCHAR(500) NOT NULL DEFAULT '',
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (subject_type, subject_id),
    KEY idx_integration_circuit_connection (connection_id, circuit_state),
    KEY idx_integration_circuit_team_state (team_id, circuit_state, open_until)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_usage_daily (
    usage_date DATE NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    connection_id VARCHAR(64) NOT NULL,
    tool_snapshot_id VARCHAR(64) NOT NULL,
    call_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    success_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    failure_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    input_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    output_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    estimated_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (usage_date, team_id, connection_id, tool_snapshot_id),
    KEY idx_integration_usage_team_date (team_id, usage_date)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_artifacts (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    team_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(64) NOT NULL,
    connection_id VARCHAR(64) NOT NULL,
    artifact_type VARCHAR(48) NOT NULL,
    content_hash CHAR(64) NOT NULL,
    encrypted_value LONGTEXT NOT NULL,
    key_version VARCHAR(32) NOT NULL,
    content_type VARCHAR(120) NOT NULL DEFAULT 'application/octet-stream',
    expires_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    KEY idx_integration_artifact_team_created (team_id, created_at),
    KEY idx_integration_artifact_expiry (expires_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_local_runner_pairings (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    code_hash CHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(64) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    device_name VARCHAR(160) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    consumed_at DATETIME(3) NULL,
    runner_id VARCHAR(64) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_local_runner_pairing_code (code_hash),
    KEY idx_local_runner_pairing_expiry (expires_at, consumed_at),
    KEY idx_local_runner_pairing_team (team_id, created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_local_runners (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    team_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(64) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    runner_status VARCHAR(24) NOT NULL,
    token_hash CHAR(64) NOT NULL,
    token_fingerprint VARCHAR(16) NOT NULL,
    hostname VARCHAR(200) NOT NULL DEFAULT '',
    platform_name VARCHAR(80) NOT NULL DEFAULT '',
    runner_version VARCHAR(40) NOT NULL DEFAULT '',
    codex_version VARCHAR(80) NOT NULL DEFAULT '',
    capabilities_json JSON NOT NULL,
    workspaces_json JSON NOT NULL,
    last_seen_at DATETIME(3) NULL,
    last_error VARCHAR(1000) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    revoked_at DATETIME(3) NULL,
    UNIQUE KEY uk_local_runner_token (token_hash),
    KEY idx_local_runner_team_updated (team_id, updated_at),
    KEY idx_local_runner_owner_updated (owner_id, updated_at),
    KEY idx_local_runner_status_seen (runner_status, last_seen_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_local_runner_tasks (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    runner_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(64) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    adapter VARCHAR(32) NOT NULL,
    prompt_text LONGTEXT NOT NULL,
    workspace_path VARCHAR(1000) NOT NULL,
    execution_mode VARCHAR(24) NOT NULL,
    timeout_seconds INT UNSIGNED NOT NULL,
    task_status VARCHAR(24) NOT NULL,
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    lease_hash CHAR(64) NOT NULL DEFAULT '',
    lease_expires_at DATETIME(3) NULL,
    cancel_requested_at DATETIME(3) NULL,
    result_text LONGTEXT NULL,
    error_message VARCHAR(4000) NOT NULL DEFAULT '',
    output_truncated TINYINT(1) NOT NULL DEFAULT 0,
    codex_thread_id VARCHAR(100) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL,
    queued_at DATETIME(3) NOT NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    updated_at DATETIME(3) NOT NULL,
    KEY idx_local_runner_task_runner_queue (runner_id, task_status, queued_at),
    KEY idx_local_runner_task_team_created (team_id, created_at),
    KEY idx_local_runner_task_owner_created (owner_id, created_at),
    KEY idx_local_runner_task_lease (task_status, lease_expires_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS integration_local_runner_task_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL,
    runner_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(24) NOT NULL,
    message TEXT NOT NULL,
    payload_json JSON NOT NULL,
    created_at DATETIME(3) NOT NULL,
    KEY idx_local_runner_event_task (task_id, id),
    KEY idx_local_runner_event_team (team_id, created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`
] as const;

export async function ensureIntegrationSchema(pool: SchemaExecutor): Promise<void> {
  for (const statement of schemaStatements) await pool.query(statement);
  await ensureColumn(pool, "integration_connections", "server_info_json", "JSON NULL");
  await ensureColumn(pool, "integration_connections", "warning_message", "VARCHAR(500) NOT NULL DEFAULT ''");
  await ensureColumn(pool, "integration_connections", "last_health_latency_ms", "INT UNSIGNED NOT NULL DEFAULT 0");
  await ensureColumn(pool, "integration_connections", "webhook_public_id", "VARCHAR(80) NOT NULL DEFAULT ''");
  await pool.query("UPDATE integration_connections SET webhook_public_id=CONCAT('iwp_',REPLACE(UUID(),'-','')) WHERE webhook_public_id=''");
  await ensureIndex(pool, "integration_connections", "uk_integration_connection_webhook_public", "UNIQUE KEY `uk_integration_connection_webhook_public` (`webhook_public_id`)");
  await ensureColumn(pool, "integration_tool_snapshots", "stable_alias", "VARCHAR(200) NOT NULL DEFAULT ''");
  await ensureColumn(pool, "integration_tool_snapshots", "permission_code", "VARCHAR(80) NOT NULL DEFAULT ''");
  await ensureColumn(pool, "integration_tool_snapshots", "review_json", "JSON NULL");
  await ensureColumn(pool, "integration_tool_calls", "input_artifact_id", "VARCHAR(64) NOT NULL DEFAULT ''");
  await ensureColumn(pool, "integration_tool_calls", "result_artifact_id", "VARCHAR(64) NOT NULL DEFAULT ''");
  await ensureColumn(pool, "integration_tool_calls", "actor_auth_version", "INT UNSIGNED NOT NULL DEFAULT 1");
  await ensureColumn(pool, "integration_events", "result_json", "JSON NULL");
  await ensureColumn(pool, "integration_events", "result_artifact_id", "VARCHAR(64) NOT NULL DEFAULT ''");
  await ensureColumn(pool, "integration_events", "writeback_status", "VARCHAR(24) NOT NULL DEFAULT 'not_applicable'");
  await ensureColumn(pool, "integration_events", "linked_object_id", "VARCHAR(64) NOT NULL DEFAULT ''");
  await ensureColumn(pool, "integration_events", "business_written_at", "DATETIME(3) NULL");
  await ensureColumn(pool, "integration_events", "last_error_code", "VARCHAR(100) NOT NULL DEFAULT ''");
  await ensureColumn(pool, "integration_events", "last_error_message", "VARCHAR(1000) NOT NULL DEFAULT ''");
  await ensureColumn(pool, "integration_events", "processing_lease_id", "VARCHAR(64) NOT NULL DEFAULT ''");
  await ensureColumn(pool, "integration_events", "processing_lease_expires_at", "DATETIME(3) NULL");
  await ensureIndex(pool, "integration_events", "idx_integration_event_lease", "KEY `idx_integration_event_lease` (`event_status`, `processing_lease_expires_at`)");
}

async function ensureColumn(pool: SchemaExecutor, table: string, column: string, definition: string) {
  const [rows] = await pool.query(
    "SELECT COUNT(*) AS count FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = ? AND column_name = ?",
    [table, column]
  );
  const count = Number((rows as Array<{ count: number }>)[0]?.count || 0);
  if (!count) await pool.query(`ALTER TABLE \`${table}\` ADD COLUMN \`${column}\` ${definition}`);
}

async function ensureIndex(pool: SchemaExecutor, table: string, index: string, definition: string) {
  const [rows] = await pool.query(
    "SELECT COUNT(*) AS count FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = ? AND index_name = ?",
    [table, index]
  );
  const count = Number((rows as Array<{ count: number }>)[0]?.count || 0);
  if (!count) await pool.query(`ALTER TABLE \`${table}\` ADD ${definition}`);
}
